name = "MOD_TITLE"
author = "DartRuffian"
prefix = "MOD_PREFIX"
mainprefix = "z"

[version]
major = 1
minor = 0
patch = 0
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_MOD_PREFIX.png",
    "logo_MOD_PREFIX_ca.paa",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"